services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: f1web_django
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - .:/app
    ports:
      - "5002:8000"
    environment:
      DEBUG: 1
      SECRET_KEY: your-secret-key
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: f1web_db
    environment:
      POSTGRES_USER: your-db-user
      POSTGRES_PASSWORD: your-db-password
      POSTGRES_DB: your-db-name
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: