# Generated by Django 5.2.1 on 2025-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True)),
                ('año_fundación', models.IntegerField()),
                ('campeonatos', models.IntegerField(default=0)),
            ],
        ),
    ]
