# Generated by Django 5.2 on 2025-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CorredorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("pais", models.CharField(max_length=50)),
                ("equipo", models.CharField(max_length=100)),
                ("numero_auto", models.IntegerField()),
                ("puntos", models.IntegerField()),
                ("foto_url", models.URLField()),
                ("edad", models.IntegerField(blank=True, null=True)),
                ("podios", models.IntegerField(default=0)),
                ("victorias", models.IntegerField(default=0)),
            ],
        ),
    ]
